global:
  tokens:
    google: ?
    mapbox: ?
    quandl: ?
slots:
  - widgets:
    - module: weather
      config:
        lat: ?
        lng: ?
        name: San Jose

    - module: city-map
      config:
        lat: ?
        lng: ?
        zoom: 13

    - module: html-content
      config:
        url: http://samir.zillie.io/

  - widgets:
    - module: equation
      config:
        formula: ?

    - module: stock
      config:
        symbol: GOOG

    - module: daily-quote
      config: No

  - widgets:
    - module: chart
      config:
        series: ?

    - module: clock
      config:
        color: ?
        state: NY
        city: New York

    - module: daily-photo
      config: No
